### ISSUE TITLE
Some duplicate key errors in apache.error.log

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Server#57]
Dear,

I have notice this error on my instance.

```
[Wed Dec 11 11:52:25.129870 2024] [php:error] [pid 2760655] [client 10.10.7.114:51708] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4c4c4544-0036-4e10-805a-c4c04f324233' for key 'uid' in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php:589\nStack trace:\n#0 /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php(589): PDOStatement->execute()\n#1 /var/www/OCO-Server-1.1.2/frontend/api-agent.php(447): DatabaseController->updateComputerInventoryValues()\n#2 {main}\n  thrown in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php on line 589
[Wed Dec 11 11:52:45.329164 2024] [php:error] [pid 2760656] [client 10.10.7.114:37314] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4C4C4544-0054-5710-8030-B4C04F563434' for key 'uid' in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php:589\nStack trace:\n#0 /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php(589): PDOStatement->execute()\n#1 /var/www/OCO-Server-1.1.2/frontend/api-agent.php(447): DatabaseController->updateComputerInventoryValues()\n#2 {main}\n  thrown in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php on line 589
[Wed Dec 11 11:53:27.472807 2024] [php:error] [pid 2869824] [client 10.10.7.114:41902] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4c4c4544-0036-4e10-805a-c4c04f324233' for key 'uid' in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php:589\nStack trace:\n#0 /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php(589): PDOStatement->execute()\n#1 /var/www/OCO-Server-1.1.2/frontend/api-agent.php(447): DatabaseController->updateComputerInventoryValues()\n#2 {main}\n  thrown in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php on line 589
[Wed Dec 11 11:54:26.111829 2024] [php:error] [pid 2626117] [client 10.10.7.114:55726] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4C4C4544-0054-5710-8030-B4C04F563434' for key 'uid' in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php:589\nStack trace:\n#0 /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php(589): PDOStatement->execute()\n#1 /var/www/OCO-Server-1.1.2/frontend/api-agent.php(447): DatabaseController->updateComputerInventoryValues()\n#2 {main}\n  thrown in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php on line 589
[Wed Dec 11 11:54:29.921852 2024] [php:error] [pid 2626118] [client 10.10.7.114:57728] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4c4c4544-0036-4e10-805a-c4c04f324233' for key 'uid' in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php:589\nStack trace:\n#0 /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php(589): PDOStatement->execute()\n#1 /var/www/OCO-Server-1.1.2/frontend/api-agent.php(447): DatabaseController->updateComputerInventoryValues()\n#2 {main}\n  thrown in /var/www/OCO-Server-1.1.2/lib/DatabaseController.class.php on line 589
```

Thank you

**Comment by BornTKill** [comment]
OK found that is because i had a the 2 computers with the same SN but different names.
So the last that have been register generate duplicate entry while inventoring.

With few select in mysql i found the problem 👍 
`select * from computer where uid = '4c4c4544-0036-4e10-805a-c4c04f324233';

`Regards.
